export enum CityCategory {
  Warszawa = 'Warszawa',
  Kraków = 'Kraków',
  Łódź = 'Łódź',
  Wrocław = 'Wrocław',
  Poznań = 'Poznań',
  Trójmiasto = 'Trójmiasto',
  Szczecin = 'Szczecin',
  Bydgoszcz = 'Bydgoszcz',
  Lublin = 'Lublin',
  Białystok = 'Białystok',
  Katowice = 'Katowice',
  Częstochowa = 'Częstochowa',
  Olsztyn = 'Olsztyn',
  ZielonaGóra = 'Zielona Góra',
}

export const CityCategoryCollection = [
  'Warszawa',
  'Kraków',
  'Łódź',
  'Wrocław',
  'Poznań',
  'Trójmiasto',
  'Szczecin',
  'Bydgoszcz',
  'Lublin',
  'Białystok',
  'Katowice',
  'Częstochowa',
  'Olsztyn',
  'Zielona Góra',
];
